#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
vprbe_bath_relaxed.py

Implements Huzinaga projection based embedding, including a one-density
variational PRBE variant with fixed D^B and optimized D^A. 

author: Ardavan Farahvash, github.com/afarahva
"""

import numpy as np
from pyscf import scf, dft, df
from pyscf.scf import chkfile
from pyscf.lib import logger, diis
from functools import partial

from pyscf import __config__
from pyscf_embedding.dft.prbe import rPRBE, uPRBE
from pyscf_embedding.dft.vprbe import (rVPRBE, uVPRBE, _energy_elec0,
                                        one_density_huzinaga_kernel)

TIGHT_GRAD_CONV_TOL = getattr(__config__, 'scf_hf_kernel_tight_grad_conv_tol', True)

# =============================================================================
# Freeze-thaw / sequential system-bath optimization
# =============================================================================
# This variant alternates two fully converged inner optimizations:
#   1. Fix D^B and optimize D^A with the one-density PRBE active solver.
#   2. Fix D^A and optimize D^B at the low level in the fixed bath space.
# The outer macrocycle checks total energy and the active-space gradient.  The
# active-space density change is printed as a diagnostic but is not a separate
# convergence threshold.

def _symmetrize(a):
    a = np.asarray(a)
    if a.ndim == 3:
        return 0.5 * (a + a.transpose(0, 2, 1))
    return 0.5 * (a + a.T)


def _generalized_eigh(f, s):
    """Small generalized Hermitian eigenproblem helper."""
    from scipy import linalg
    f = _symmetrize(f)
    s = _symmetrize(s)
    e, c = linalg.eigh(f, s)
    idx = np.argsort(e)
    return e[idx], c[:, idx]


def _restricted_subspace_scf_update(fock, s1e, space, nocc, occ_value=2.0):
    """
    Diagonalize a Fock matrix in a fixed restricted subspace and return
    mo_energy, mo_coeff, mo_occ, and the corresponding density matrix.
    """
    if space.shape[1] == 0:
        nao = s1e.shape[0]
        return (np.array([]), np.zeros((nao, 0)), np.array([]),
                np.zeros((nao, nao)))

    f_sub = space.T @ fock @ space
    s_sub = space.T @ s1e @ space
    eps, c_sub = _generalized_eigh(f_sub, s_sub)
    coeff = space @ c_sub

    mo_occ = np.zeros(eps.size)
    mo_occ[:nocc] = occ_value
    dm = (coeff * mo_occ) @ coeff.T
    return eps, coeff, mo_occ, dm


def _unrestricted_subspace_scf_update(fock, s1e, spaces, noccs):
    """
    Spin-resolved fixed-subspace update.  `fock` has shape (2, nao, nao),
    `spaces` is a pair of AO coefficient matrices, and `noccs` is (na, nb).
    """
    eps = []
    coeff = []
    occ = []
    dm = []
    for spin in range(2):
        e_s, c_s, occ_s, dm_s = _restricted_subspace_scf_update(
            fock[spin], s1e, spaces[spin], noccs[spin], occ_value=1.0
        )
        eps.append(e_s)
        coeff.append(c_s)
        occ.append(occ_s)
        dm.append(dm_s)
    return tuple(eps), tuple(coeff), tuple(occ), np.asarray(dm)


def _bath_fixed_active_build(mf_low, dm_A_fixed, dm_B):
    """
    Build the low-level bath Fock for fixed active density D_A.

    With D_A fixed, the bath Euler equation is generated by
        F_B = F_2[D_A + D_B].
    The hcore_eff_B returned here is useful only if one wants to represent this
    Fock as hcore_eff_B + V_2[D_B].
    """
    mol = mf_low.mol
    h0 = mf_low.get_hcore(mol)
    dm_tot = dm_A_fixed + dm_B
    v2_tot = mf_low.get_veff(mol, dm_tot)
    v2_B = mf_low.get_veff(mol, dm_B)
    hcore_eff_B = h0 + v2_tot - v2_B
    fock_B = h0 + v2_tot
    e_low_tot = mf_low.energy_tot(dm=dm_tot, h1e=h0, vhf=v2_tot)
    return fock_B, hcore_eff_B, v2_tot, v2_B, e_low_tot


def bath_fixed_active_kernel(mf_low, dm_A_fixed, space_B, nocc_B, dm_B0,
                             unrestricted=False, conv_tol=1e-8,
                             conv_tol_grad=None, max_cycle=None,
                             damping=0.0, callback=None):
    """
    Optimize D^B with D^A fixed, within the fixed bath orbital space.

    This is an inner bath-only SCF.  It does not decide the final embedding
    convergence; it simply relaxes the bath for the current active density.
    """
    cput0 = (logger.process_clock(), logger.perf_counter())
    if conv_tol_grad is None:
        conv_tol_grad = np.sqrt(conv_tol)
    if max_cycle is None:
        max_cycle = mf_low.max_cycle

    mol = mf_low.mol
    s1e = mf_low.get_ovlp(mol)
    dm_B = np.array(dm_B0, copy=True)

    fock_B, hcore_eff_B, v2_tot, v2_B, e_low = _bath_fixed_active_build(
        mf_low, dm_A_fixed, dm_B
    )

    scf_conv = False
    mo_energy_B = mo_coeff_B = mo_occ_B = None

    logger.info(mf_low, 'init fixed-A bath relaxation E2[D_A+D_B]= %.15g', e_low)

    for cycle in range(max_cycle):
        dm_B_last = np.array(dm_B, copy=True)
        last_e = e_low

        if unrestricted:
            mo_energy_B, mo_coeff_B, mo_occ_B, dm_B_new = \
                _unrestricted_subspace_scf_update(fock_B, s1e, space_B, nocc_B)
        else:
            mo_energy_B, mo_coeff_B, mo_occ_B, dm_B_new = \
                _restricted_subspace_scf_update(fock_B, s1e, space_B, nocc_B)

        if damping:
            dm_B = (1.0 - damping) * dm_B_new + damping * dm_B_last
        else:
            dm_B = dm_B_new

        fock_B, hcore_eff_B, v2_tot, v2_B, e_low = _bath_fixed_active_build(
            mf_low, dm_A_fixed, dm_B
        )

        grad_B = mf_low.get_grad(mo_coeff_B, mo_occ_B, fock_B)
        norm_gorb_B = np.linalg.norm(grad_B)
        if not TIGHT_GRAD_CONV_TOL:
            norm_gorb_B = norm_gorb_B / np.sqrt(grad_B.size)
        norm_ddm_B = np.linalg.norm(dm_B - dm_B_last)

        logger.info(mf_low,
            'bath cycle= %d E2[D_A+D_B]= %.15g  delta_E= %4.3g  |g_B|= %4.3g  |ddm_B|= %4.3g',
            cycle + 1, e_low, e_low - last_e, norm_gorb_B, norm_ddm_B)

        if abs(e_low - last_e) < conv_tol and norm_gorb_B < conv_tol_grad:
            scf_conv = True

        if callable(callback):
            callback(locals())

        if scf_conv:
            break

    if damping:
        if unrestricted:
            mo_energy_B, mo_coeff_B, mo_occ_B, dm_B = \
                _unrestricted_subspace_scf_update(fock_B, s1e, space_B, nocc_B)
        else:
            mo_energy_B, mo_coeff_B, mo_occ_B, dm_B = \
                _restricted_subspace_scf_update(fock_B, s1e, space_B, nocc_B)
        fock_B, hcore_eff_B, v2_tot, v2_B, e_low = _bath_fixed_active_build(
            mf_low, dm_A_fixed, dm_B
        )

    logger.timer(mf_low, 'fixed_A_bath_relaxation', *cput0)
    return scf_conv, e_low, mo_energy_B, mo_coeff_B, mo_occ_B, dm_B


def _active_gradient_norm(mf_A, dm_A=None):
    """Return the orbital gradient norm for the current active embedded MF state."""
    if dm_A is None:
        dm_A = mf_A.make_rdm1()
    s1e = mf_A.get_ovlp(mf_A.mol)
    vhf_A = mf_A.get_veff(mf_A.mol, dm_A)
    h1e_A = mf_A.get_hcore(mf_A.mol)
    fock_A = mf_A.get_fock(h1e_A, s1e, vhf_A, dm_A)
    grad_A = mf_A.get_grad(mf_A.mo_coeff, mf_A.mo_occ, fock_A)
    norm_gorb_A = np.linalg.norm(grad_A)
    if not TIGHT_GRAD_CONV_TOL:
        norm_gorb_A = norm_gorb_A / np.sqrt(grad_A.size)
    return norm_gorb_A


def _run_active_freeze_thaw_step(mf_A, mf_B, dm_A, dm_B, P_occ_B, P_vir_B,
                                 conv_tol=1e-8, conv_tol_grad=None,
                                 max_cycle=None):
    """Optimize D^A with D^B fixed using the one-density Huzinaga kernel."""
    old_max_cycle = mf_A.max_cycle
    if max_cycle is not None:
        mf_A.max_cycle = max_cycle
    try:
        out = one_density_huzinaga_kernel(
            mf=mf_A, mf_B=mf_B, dm_B=dm_B, dm0=dm_A,
            conv_tol=conv_tol, conv_tol_grad=conv_tol_grad,
            P_occ_B=P_occ_B, P_vir_B=P_vir_B
        )
    finally:
        mf_A.max_cycle = old_max_cycle

    mf_A.converged, mf_A.e_tot, mf_A.mo_energy, mf_A.mo_coeff, mf_A.mo_occ = out
    dm_A = mf_A.make_rdm1()
    norm_gorb_A = _active_gradient_norm(mf_A, dm_A=dm_A)
    return dm_A, norm_gorb_A, out

def _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B):
    """
    Build active/bath Fock matrices and the total bath-relaxed PRBE energy for
    the current pair of densities.
    """
    mol_A = mf_A.mol
    mol_B = mf_B.mol
    h0 = mf_B.get_hcore(mol_B)
    dm_AB = dm_A + dm_B

    v2_AB = mf_B.get_veff(mol_B, dm_AB)
    v2_A = mf_B.get_veff(mol_B, dm_A)
    v1_A = mf_A.get_veff(mol_A, dm_A)

    fock_A = h0 + v1_A + v2_AB - v2_A
    fock_B = h0 + v2_AB
    hcore_A = h0 + v2_AB - v2_A

    e2_AB_tot = mf_B.energy_tot(dm=dm_AB, h1e=h0, vhf=v2_AB)
    e1_A_elec = _energy_elec0(mf_A, dm_A, h0, v1_A)
    e2_A_elec = _energy_elec0(mf_B, dm_A, h0, v2_A)
    e_prbe = e2_AB_tot + e1_A_elec - e2_A_elec

    return fock_A, fock_B, hcore_A, v1_A, v2_AB, v2_A, e_prbe


def _filter_restricted_active_mos(mf_A, ovlp, moC_occ_B, moC_vir_B,
                                  epsilon=1e-5):
    """Remove bath-overlapping orbitals from a restricted embedded MF object."""
    bath_orbs = np.hstack([moC_occ_B, moC_vir_B])
    if bath_orbs.shape[1] == 0:
        return

    mask_act = np.linalg.norm(mf_A.mo_coeff.T @ ovlp @ bath_orbs,
                              axis=1) <= epsilon
    mf_A.mo_energy = mf_A.mo_energy[mask_act]
    mf_A.mo_coeff = mf_A.mo_coeff[:, mask_act]
    mf_A.mo_occ = mf_A.mo_occ[mask_act]


def _filter_unrestricted_active_mos(mf_A, ovlp, moC_occ_B, moC_vir_B,
                                    epsilon=1e-5):
    """Remove bath-overlapping orbitals from an unrestricted embedded MF object."""
    mo_energy = list(mf_A.mo_energy)
    mo_coeff = list(mf_A.mo_coeff)
    mo_occ = list(mf_A.mo_occ)

    for spin in range(2):
        bath_orbs = np.hstack([moC_occ_B[spin], moC_vir_B[spin]])
        if bath_orbs.shape[1] == 0:
            continue

        mask_act = np.linalg.norm(mo_coeff[spin].T @ ovlp @ bath_orbs,
                                  axis=1) <= epsilon
        mo_energy[spin] = mo_energy[spin][mask_act]
        mo_coeff[spin] = mo_coeff[spin][:, mask_act]
        mo_occ[spin] = mo_occ[spin][mask_act]

    mf_A.mo_energy = tuple(mo_energy)
    mf_A.mo_coeff = tuple(mo_coeff)
    mf_A.mo_occ = tuple(mo_occ)


class rVPRBEFreezeThaw(rVPRBE):
    """
    Restricted freeze-thaw one-density PRBE.

    Alternates fixed-bath active optimization and fixed-active bath relaxation.
    The active step uses the existing one-density Huzinaga PRBE kernel, so it
    retains the usual active-space DIIS machinery.  The bath step is optimized
    independently in the fixed bath orbital space.
    """
    
    
    def make_active_space(self):
        return np.hstack([self.moC_occ_A, self.moC_vir_A])

    def make_bath_space(self):
        return np.hstack([self.moC_occ_B, self.moC_vir_B])

    def kernel(self, xc_embed=None, ecp_embed=None, pseudo_embed=None,
               max_macro=20, max_cycle_A=None, max_cycle_B=None,
               conv_tol_macro=None, conv_tol_grad=None, damping_B=0.0,
               final_active=True, **kwargs):
        mf_B = self.mf_B
        mol = mf_B.mol.copy()
        nocc_A = self.moC_occ_A.shape[1]
        nocc_B = self.moC_occ_B.shape[1]
        mol.nelectron = int(2 * nocc_A)

        if conv_tol_macro is None:
            conv_tol_macro = 1e-8
        if conv_tol_grad is None:
            conv_tol_grad = np.sqrt(conv_tol_macro)

        dm_A = self.make_rdmA_init()
        dm_B = self.make_rdmB_fixed()

        if xc_embed is None:
            self.mf_A = scf.RHF(mol, **kwargs)
        else:
            self.mf_A = dft.RKS(mol)
            self.mf_A.xc = xc_embed

        if hasattr(mf_B, 'with_df'):
            self.mf_A = df.density_fit(self.mf_A)
            self.mf_A.with_df.auxbasis = mf_B.with_df.auxbasis

        mf_A = self.mf_A
        mf_A.diis_space = mf_B.diis_space
        mf_A.diis_damp = mf_B.diis_damp
        mf_A.max_cycle = mf_B.max_cycle
        mf_A.verbose = mf_B.verbose

        P_occ_B = self.moC_occ_B @ self.moC_occ_B.T
        P_vir_B = self.moC_vir_B @ self.moC_vir_B.T
        space_B = self.make_bath_space()

        _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)
        logger.info(mf_A, 'init freeze-thaw PRBE E= %.15g', e_tot)

        scf_conv = False
        norm_gorb_A = np.inf
        for macro in range(max_macro):
            dm_A_macro_last = np.array(dm_A, copy=True)
            last_e = e_tot

            # A step: fixed bath, active PRBE optimization.
            dm_A, norm_gorb_A, _ = _run_active_freeze_thaw_step(
                mf_A, mf_B, dm_A, dm_B, P_occ_B, P_vir_B,
                conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                max_cycle=max_cycle_A
            )

            # B step: fixed active density, low-level bath relaxation.
            _, _, self.mo_energy_B, self.mo_coeff_B, self.mo_occ_B, dm_B = \
                bath_fixed_active_kernel(
                    mf_low=mf_B, dm_A_fixed=dm_A, space_B=space_B,
                    nocc_B=nocc_B, dm_B0=dm_B, unrestricted=False,
                    conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                    max_cycle=max_cycle_B, damping=damping_B
                )

            # Rebuild Huzinaga projectors from the relaxed bath occupations.
            mask_occ = self.mo_occ_B > 0.5
            P_occ_B = self.mo_coeff_B[:, mask_occ] @ self.mo_coeff_B[:, mask_occ].T
            P_vir_B = self.mo_coeff_B[:, ~mask_occ] @ self.mo_coeff_B[:, ~mask_occ].T

            _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)
            norm_ddm_A = np.linalg.norm(dm_A - dm_A_macro_last)

            logger.info(mf_A,
                'macro= %d freeze-thaw PRBE E= %.15g  delta_E= %4.3g  |g_A|= %4.3g  |ddm_A|= %4.3g',
                macro + 1, e_tot, e_tot - last_e, norm_gorb_A, norm_ddm_A)

            if abs(e_tot - last_e) < conv_tol_macro and norm_gorb_A < conv_tol_grad:
                scf_conv = True
                break

        # End on an active optimization so the orbitals handed to CC are
        # stationary with respect to the final relaxed bath.
        if final_active:
            dm_A, norm_gorb_A, _ = _run_active_freeze_thaw_step(
                mf_A, mf_B, dm_A, dm_B, P_occ_B, P_vir_B,
                conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                max_cycle=max_cycle_A
            )
            _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)

        self.e_tot = e_tot
        self.dm_A = dm_A
        self.dm_B = dm_B
        _filter_restricted_active_mos(
            mf_A, mf_B.get_ovlp(), self.moC_occ_B, self.moC_vir_B
        )
        mf_A.e_tot = e_tot
        mf_A.converged = scf_conv
        mf_A.prbe_dm_A = dm_A
        mf_A.prbe_dm_B = dm_B
        mf_A.prbe_mo_energy_B = getattr(self, 'mo_energy_B', None)
        mf_A.prbe_mo_coeff_B = getattr(self, 'mo_coeff_B', None)
        mf_A.prbe_mo_occ_B = getattr(self, 'mo_occ_B', None)

        self.e_tot -= self.calc_disp_embed()
        mf_A.e_tot = self.e_tot
        logger.info(mf_A, 'final freeze-thaw PRBE E= %.15g  |g_A|= %4.3g',
                    self.e_tot, norm_gorb_A)
        return self.e_tot, mf_A.mo_energy, mf_A.mo_coeff, mf_A.mo_occ


class uVPRBEFreezeThaw(uVPRBE):
    """Unrestricted freeze-thaw one-density PRBE."""
    
    def make_active_space(self):
        return (np.hstack([self.moC_occ_A[0], self.moC_vir_A[0]]),
                np.hstack([self.moC_occ_A[1], self.moC_vir_A[1]]))

    def make_bath_space(self):
        return (np.hstack([self.moC_occ_B[0], self.moC_vir_B[0]]),
                np.hstack([self.moC_occ_B[1], self.moC_vir_B[1]]))


    def kernel(self, xc_embed=None, ecp_embed=None, pseudo_embed=None,
               max_macro=20, max_cycle_A=None, max_cycle_B=None,
               conv_tol_macro=None, conv_tol_grad=None, damping_B=0.0,
               final_active=True, **kwargs):
        mf_B = self.mf_B
        mol = mf_B.mol.copy()
        nocc_A = (self.moC_occ_A[0].shape[1], self.moC_occ_A[1].shape[1])
        nocc_B = (self.moC_occ_B[0].shape[1], self.moC_occ_B[1].shape[1])
        n_alpha, n_beta = nocc_A
        mol.nelectron = int(n_alpha + n_beta)
        mol.spin = int(n_alpha - n_beta)

        if conv_tol_macro is None:
            conv_tol_macro = 1e-8
        if conv_tol_grad is None:
            conv_tol_grad = np.sqrt(conv_tol_macro)

        dm_A = self.make_rdmA_init()
        dm_B = self.make_rdmB_fixed()

        if xc_embed is None:
            self.mf_A = scf.UHF(mol, **kwargs)
        else:
            self.mf_A = dft.UKS(mol)
            self.mf_A.xc = xc_embed

        if hasattr(mf_B, 'with_df'):
            self.mf_A = df.density_fit(self.mf_A)
            self.mf_A.with_df.auxbasis = mf_B.with_df.auxbasis

        mf_A = self.mf_A
        mf_A.diis_space = mf_B.diis_space
        mf_A.diis_damp = mf_B.diis_damp
        mf_A.max_cycle = mf_B.max_cycle
        mf_A.verbose = mf_B.verbose

        P_occ_B = np.array([
            self.moC_occ_B[0] @ self.moC_occ_B[0].T,
            self.moC_occ_B[1] @ self.moC_occ_B[1].T,
        ])
        P_vir_B = np.array([
            self.moC_vir_B[0] @ self.moC_vir_B[0].T,
            self.moC_vir_B[1] @ self.moC_vir_B[1].T,
        ])
        space_B = self.make_bath_space()

        _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)
        logger.info(mf_A, 'init freeze-thaw PRBE E= %.15g', e_tot)

        scf_conv = False
        norm_gorb_A = np.inf
        for macro in range(max_macro):
            dm_A_macro_last = np.array(dm_A, copy=True)
            last_e = e_tot

            dm_A, norm_gorb_A, _ = _run_active_freeze_thaw_step(
                mf_A, mf_B, dm_A, dm_B, P_occ_B, P_vir_B,
                conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                max_cycle=max_cycle_A
            )

            _, _, self.mo_energy_B, self.mo_coeff_B, self.mo_occ_B, dm_B = \
                bath_fixed_active_kernel(
                    mf_low=mf_B, dm_A_fixed=dm_A, space_B=space_B,
                    nocc_B=nocc_B, dm_B0=dm_B, unrestricted=True,
                    conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                    max_cycle=max_cycle_B, damping=damping_B
                )

            # Rebuild Huzinaga projectors from the relaxed bath occupations.
            for spin in range(2):
                mask_occ = self.mo_occ_B[spin] > 0.5
                P_occ_B[spin] = (self.mo_coeff_B[spin][:, mask_occ] @
                                  self.mo_coeff_B[spin][:, mask_occ].T)
                P_vir_B[spin] = (self.mo_coeff_B[spin][:, ~mask_occ] @
                                  self.mo_coeff_B[spin][:, ~mask_occ].T)

            _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)
            norm_ddm_A = np.linalg.norm(dm_A - dm_A_macro_last)

            logger.info(mf_A,
                'macro= %d freeze-thaw PRBE E= %.15g  delta_E= %4.3g  |g_A|= %4.3g  |ddm_A|= %4.3g',
                macro + 1, e_tot, e_tot - last_e, norm_gorb_A, norm_ddm_A)

            if abs(e_tot - last_e) < conv_tol_macro and norm_gorb_A < conv_tol_grad:
                scf_conv = True
                break

        if final_active:
            dm_A, norm_gorb_A, _ = _run_active_freeze_thaw_step(
                mf_A, mf_B, dm_A, dm_B, P_occ_B, P_vir_B,
                conv_tol=conv_tol_macro, conv_tol_grad=conv_tol_grad,
                max_cycle=max_cycle_A
            )
            _, _, _, _, _, _, e_tot = _bath_relaxed_prbe_build(mf_A, mf_B, dm_A, dm_B)

        self.e_tot = e_tot
        self.dm_A = dm_A
        self.dm_B = dm_B
        _filter_unrestricted_active_mos(
            mf_A, mf_B.get_ovlp(), self.moC_occ_B, self.moC_vir_B
        )
        mf_A.e_tot = e_tot
        mf_A.converged = scf_conv
        mf_A.prbe_dm_A = dm_A
        mf_A.prbe_dm_B = dm_B
        mf_A.prbe_mo_energy_B = getattr(self, 'mo_energy_B', None)
        mf_A.prbe_mo_coeff_B = getattr(self, 'mo_coeff_B', None)
        mf_A.prbe_mo_occ_B = getattr(self, 'mo_occ_B', None)

        self.e_tot -= self.calc_disp_embed()
        mf_A.e_tot = self.e_tot
        logger.info(mf_A, 'final freeze-thaw PRBE E= %.15g  |g_A|= %4.3g',
                    self.e_tot, norm_gorb_A)
        return self.e_tot, mf_A.mo_energy, mf_A.mo_coeff, mf_A.mo_occ


#%%
if __name__ == '__main__':
    from pyscf_embedding.local import regional as re
    from pyscf_embedding.utils import chemcore
    from pyscf import gto, scf, cc, grad

    coords1 = \
    """
      H           1.83033035325714     -1.55914459515730      0.85018703157270
      C           0.90263631613210     -0.08578242736390      0.14894116637203
      O           1.92201300538061      0.51665324420946     -0.08503290170897
      O           0.90171075857076     -1.32072671224472      0.70739805133646
      C          -0.44742060897905      0.43887835522198     -0.13930696034172
      C          -1.57631378519914     -0.21501349238018      0.11262246365465
      H          -0.44354482529961      1.42537195115242     -0.58435608510154
      H          -1.57016561414080     -1.20100172981207      0.55763852778426
      H          -2.53835159972200      0.22238440637431     -0.12155029356787
    """
    
    coords2 = \
    """
      C           0.93501939826289     -0.16731316159968      0.18715060054646
      O           1.88694577197618      0.59099117395221     -0.12029735496945
      O           0.96364675571253     -1.30644525101509      0.70374527602260
      C          -0.45331566554332      0.41330164264060     -0.12783548248701
      C          -1.60070946799917     -0.21426796566953      0.11128233993953
      H          -0.44856062322574      1.40525848237891     -0.57525090759213
      H          -1.57811875566373     -1.20278092786669      0.55806286649746
      H          -2.56689441351964      0.22480300717926     -0.12390333795747
    """
    
    # coords1 = \
    # """
    #   H          -2.33853423528445     -1.80445188593265      0.11651648020221
    #   O          -2.34422459255885     -0.85278916752672     -0.03576411026300
    #   C          -1.06258456679029     -0.37939268607129     -0.01728490895882
    #   C           0.03672552600454     -1.20674427294869      0.19587817315120
    #   C          -0.87933383150076      0.98550108666543     -0.22229854535058
    #   C           1.31693787084500     -0.66574822089220      0.20334230293598
    #   C           0.40339408165426      1.51340780309772     -0.21253603009361
    #   C           1.50876316862276      0.69480639109537     -0.00029246918990
    #   H          -1.74545802184674      1.61252309509986     -0.38639091454627
    #   H          -0.10850689384867     -2.26985861428912      0.35517200444118
    #   H           2.16662091581719     -1.31570774357644      0.36979039101203
    #   H           0.53987391557788      2.57552108882858     -0.37240095762938
    #   H           2.50632566330812      1.11293312645015      0.00626858428895
    # """
    
    # coords2 = \
    # """
    #   Cl         -2.66552880321122     -1.04648920352946     -0.02858438211425
    #   C          -1.05418475844935     -0.37402118589571     -0.01754899463371
    #   C          -0.88351585053082      0.98806033343056     -0.22302996160454
    #   C           0.03181906088976     -1.21156891873802      0.19626721449624
    #   C           0.40161946228383      1.51651330760525     -0.21314994006458
    #   C           1.31127908283482     -0.66945895604463      0.20350987507472
    #   C           1.50050564548318      0.69236009337727     -0.00049441681239
    #   H          -0.12528181587270     -2.26933992568938      0.35382176314591
    #   H          -1.74412056922073      1.62100921590816     -0.38766608487821
    #   H           0.54020920533309      2.57808841901490     -0.37274437771367
    #   H           2.16154435858189     -1.31831745634710      0.36981403020102
    #   H           2.49900198187823      1.10907027690817      0.00636727490347
    # """
    
    #%%
    ##### Calculation One, Test rPRBE
    basis='ccpvdz'
    xc = 'pbe'
    #%%
    # run CC
    mol1 = gto.Mole(atom=coords1,basis=basis,spin=0,verbose=4)
    mf1 = mol1.RHF(max_cycle=100).density_fit().run()
    mycc1 = cc.CCSD(mf1,frozen=chemcore(mol1)).density_fit()
    mycc1 = mycc1.run()
    ecc1 = mycc1.e_tot
    
    mol2 = gto.Mole(atom=coords2,basis=basis,spin=0,verbose=4,charge=-1)
    mf2 = mol2.RHF(max_cycle=100).density_fit().run()
    mycc2 = cc.CCSD(mf2,frozen=chemcore(mol2)).density_fit()
    mycc2 = mycc2.run()
    ecc2 = mycc2.e_tot
    
    del mycc1, mycc2
    #%%
    # run DFT
    mol1 = gto.Mole(atom=coords1,basis=basis,spin=0,verbose=4)
    mf1 = mol1.RKS(xc=xc,max_cycle=100).density_fit().run()
    edft1 = mf1.e_tot
    
    mol2 = gto.Mole(atom=coords2,basis=basis,spin=0,verbose=4,charge=-1)
    mf2 = mol2.RKS(xc=xc,max_cycle=100).density_fit().run()
    edft2 = mf2.e_tot
    
    #%%
    ##### standard PRBE
    
    # run embedding 1
    occ_calc = re.RegionalActiveSpace(mf1, np.arange(0,4), 'occ', basis='minao', cutoff=0.25)
    vir_calc = re.RegionalActiveSpace(mf1, np.arange(0,4), 'vir', basis=mol1.basis, cutoff=1e-6)
    _,moC_occ,mask_occ_act = occ_calc.calc_mo()
    _,moC_vir,mask_vir_act = vir_calc.calc_mo()

    embed1 = rPRBE(mf1, moC_occ, moC_vir, mask_occ_act, mask_vir_act)
    e_mf,mo_energy,mo_coeff,mo_occ = embed1.kernel(xc_embed=None)
    mycc1 = cc.CCSD(embed1.mf_A).density_fit()
    mycc1.kernel()
    e_embed1 = e_mf + mycc1.e_corr
    
    # run embedding 2
    occ_calc = re.RegionalActiveSpace(mf2, np.arange(0,3), 'occ', basis='minao', cutoff=0.25)
    vir_calc = re.RegionalActiveSpace(mf2, np.arange(0,3), 'vir', basis=mol1.basis, cutoff=1e-6)
    _,moC_occ,mask_occ_act = occ_calc.calc_mo()
    _,moC_vir,mask_vir_act = vir_calc.calc_mo()

    embed2 = rPRBE(mf2, moC_occ, moC_vir, mask_occ_act, mask_vir_act)
    e_mf,mo_energy,mo_coeff,mo_occ = embed2.kernel(xc_embed=None)
    mycc2 = cc.CCSD(embed2.mf_A).density_fit()
    mycc2.kernel()
    e_embed2 = e_mf + mycc2.e_corr
    
    print((ecc2-ecc1)*627.5095, (edft2-edft1)*627.5095, 
          (e_embed2-e_embed1)*627.5095)
    #%%
    ##### standard vPRBE
    
    # run embedding 1
    occ_calc = re.RegionalActiveSpace(mf1, np.arange(0,4), 'occ', basis='minao', cutoff=0.25)
    vir_calc = re.RegionalActiveSpace(mf1, np.arange(0,4), 'vir', basis=mol1.basis, cutoff=1e-6)
    _,moC_occ,mask_occ_act = occ_calc.calc_mo()
    _,moC_vir,mask_vir_act = vir_calc.calc_mo()

    embed1 = rVPRBEFreezeThaw(mf1, moC_occ, moC_vir, mask_occ_act, mask_vir_act)
    e_mf,mo_energy,mo_coeff,mo_occ = embed1.kernel(xc_embed=None)
    mycc1 = cc.CCSD(embed1.mf_A).density_fit()
    mycc1.max_cycle = 100 
    mycc1.kernel()
    e_vembed1 = e_mf + mycc1.e_corr
    
    # run embedding 2
    occ_calc = re.RegionalActiveSpace(mf2, np.arange(0,3), 'occ', basis='minao', cutoff=0.25)
    vir_calc = re.RegionalActiveSpace(mf2, np.arange(0,3), 'vir', basis=mol1.basis, cutoff=1e-6)
    mf2.diis_damp=0.7
    _,moC_occ,mask_occ_act = occ_calc.calc_mo()
    _,moC_vir,mask_vir_act = vir_calc.calc_mo()

    embed2 = rVPRBEFreezeThaw(mf2, moC_occ, moC_vir, mask_occ_act, mask_vir_act)
    e_mf,mo_energy,mo_coeff,mo_occ = embed2.kernel(xc_embed=None)
    mycc2 = cc.CCSD(embed2.mf_A).density_fit()
    mycc2.max_cycle = 1000 
    mycc2.kernel()
    e_vembed2 = e_mf + mycc2.e_corr
    
    print((ecc2-ecc1)*627.5095, (edft2-edft1)*627.5095, 
          (e_embed2-e_embed1)*627.5095, (e_vembed2-e_vembed1)*627.5095)
